// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGhT53j4lCpoJlspm8-vqCD3x9VWIYmI',
    appId: '1:607535217629:web:6f4ef140f4e22f91f95434',
    messagingSenderId: '607535217629',
    projectId: 'my-guider-51ede',
    authDomain: 'my-guider-51ede.firebaseapp.com',
    storageBucket: 'my-guider-51ede.firebasestorage.app',
    measurementId: 'G-Z8XS8RKCR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWAynyQAhCIJDvmH4XdnJ7jBieHg6e4I',
    appId: '1:607535217629:android:cfaeaa48a1874f05f95434',
    messagingSenderId: '607535217629',
    projectId: 'my-guider-51ede',
    storageBucket: 'my-guider-51ede.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlGOqHg42H4Zn3rH34HNeoiC4069uQbQo',
    appId: '1:607535217629:ios:527e0fd6df6382e9f95434',
    messagingSenderId: '607535217629',
    projectId: 'my-guider-51ede',
    storageBucket: 'my-guider-51ede.firebasestorage.app',
    iosBundleId: 'com.priyvratmodi.careerPathFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlGOqHg42H4Zn3rH34HNeoiC4069uQbQo',
    appId: '1:607535217629:ios:527e0fd6df6382e9f95434',
    messagingSenderId: '607535217629',
    projectId: 'my-guider-51ede',
    storageBucket: 'my-guider-51ede.firebasestorage.app',
    iosBundleId: 'com.priyvratmodi.careerPathFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkGhT53j4lCpoJlspm8-vqCD3x9VWIYmI',
    appId: '1:607535217629:web:30cb21961b6100c7f95434',
    messagingSenderId: '607535217629',
    projectId: 'my-guider-51ede',
    authDomain: 'my-guider-51ede.firebaseapp.com',
    storageBucket: 'my-guider-51ede.firebasestorage.app',
    measurementId: 'G-TJYGHTD66Z',
  );
}
